# Generated by Django 4.1.5 on 2023-07-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('DOB', models.CharField(default='', max_length=20)),
                ('Password', models.CharField(default='', max_length=20)),
                ('Course', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=20)),
                ('Mail', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
